force-app/main/default/objects/User_Credential__c/User_Credential__c.object-meta.xml
<CustomObject>
    <label>User Credential</label>
    <nameField>
        <displayFormat>CRED-{00000}</displayFormat>
        <label>User Credential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CredentialTrackingController.cls
/**
 * @author Lavanya Bonthala
 * @date   6/28/2022
 * @description Apex controller for credentialTracking component
 */
public with sharing class CredentialTrackingController {

    /*******************************************************************************************************
      * @description Returns User Credentials that are in progress
      * @param userId SF id of user
      * @return List of User Credentials
      */ 
    @AuraEnabled
    public static List<User_Credential__c> getUserCredentials(String userId)
    {
        UserCredentialService ucs = new UserCredentialService();
        List<User_Credential__c> totalUserCredentials = ucs.getActiveUserCredentials(userId);
        return totalUserCredentials;  
    } 
 
    /*******************************************************************************************************
      * @description Returns boolean value
      * @param id,status
      * @return true or false
      */
    @AuraEnabled
    public static Boolean updateUserCredential(String id, string status)
    {
         UserCredentialService ucs = new UserCredentialService();
         List<User_Credential__c> userCredentials = new List<User_Credential__c>{new User_Credential__c(id=id,status__c=status)};
         List<Database.SaveResult> srList = ucs.updateUserCredentials(userCredentials);
         
         Boolean isSuccess= true;
         for (Database.SaveResult sr : srList) {
             if (sr.isSuccess()) {
                 //console.log(sr.getId());
                                 }else {isSuccess =false; for(Database.Error err : sr.getErrors()) {
                                    // console.log(err.getMessage());
                                 }
             }
         }
         return isSuccess; 
    } 
 }