force-app/main/default/objects/Exam_Voucher__c/Exam_Voucher__c.object-meta.xml
<CustomObject>
    <label>Exam Voucher</label>
    <nameField>
        <displayFormat>VC-{000000}</displayFormat>
        <label>Exam Voucher ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam_Voucher__c/fields/Credential_Type__c.field-meta.xml
<CustomField>
    <fullName>Credential_Type__c</fullName>
    <label>Credential Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Credential_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <label>Sponsor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Credential_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Trailhead</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>MuleSoft</fullName>
    </customValue>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VoucherAssignmentService.cls
/**
 * @author Dipshika Nalawade
 * @date   16/09/2022
 * @description Service Class containing methods specific to Voucher Assignment
 */
public with sharing class VoucherAssignmentService {
    /*******************************************************************************************************
     * @description This method retrieves all vouchers Admin have
     * @return List of Exam Vouchers
     */
    public List<Exam_Voucher__c> getAvailableExamVouchers(string credType, integer credentialCost) {
        try {
            return [
                SELECT id, Credential_Type__c, Name, Cost__c, Value__c, Sponsor__c, Expiry_Date__c
                FROM Exam_Voucher__c
                WHERE Credential_Type__c = :credType AND Cost__c >= :credentialCost
                WITH SECURITY_ENFORCED
            ];
        } catch (Exception ex) {
            throw ex;
        }
    }
}