force-app/main/default/objects/Exam_Voucher__c/Exam_Voucher__c.object-meta.xml
<CustomObject>
    <label>Exam Voucher</label>
    <nameField>
        <displayFormat>VC-{000000}</displayFormat>
        <label>Exam Voucher ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam_Voucher__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Voucher Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Voucher_Code_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code_Encrypted__c</fullName>
    <label>Voucher Code Encrypted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Voucher_Code_Masked__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code_Masked__c</fullName>
    <label>Voucher Code Masked</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Practice_Studio_Setting__mdt/Practice_Studio_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Practice Studio Setting</label>
    <pluralLabel>Practice Studio Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Practice_Studio_Setting__mdt/fields/Algorithm_Name__c.field-meta.xml
<CustomField>
    <fullName>Algorithm_Name__c</fullName>
    <label>Algorithm Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Practice_Studio_Setting__mdt/fields/Initialization_Vector__c.field-meta.xml
<CustomField>
    <fullName>Initialization_Vector__c</fullName>
    <label>Initialization Vector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Practice_Studio_Setting__mdt/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExamVoucherService.cls
global with sharing class ExamVoucherService {
  public class ExamVoucherException extends Exception {}
  public static List<Exam_Voucher__c> setVoucherCodeEncrypted(
    List<Exam_Voucher__c> examVouchers
  ) {
    Practice_Studio_Setting__mdt defaultSetting = getEncryptionConfig();
    for (Exam_Voucher__c examVoucher : examVouchers) {
      Blob encryptedVoucher = Crypto.encrypt(defaultSetting.Algorithm_Name__c, EncodingUtil.base64Decode(defaultSetting.Private_Key__c), Blob.valueOf(defaultSetting.Initialization_Vector__c), Blob.valueOf(examVoucher.Voucher_Code__c));
      String encryptedVoucherString = EncodingUtil.base64Encode(encryptedVoucher);
      examVoucher.Voucher_Code_Encrypted__c = encryptedVoucherString;
    }
    return examVouchers;
  }

  public static List<Exam_Voucher__c> setVoucherCodeMasked(
    List<Exam_Voucher__c> examVouchers
  ) {

    String regExp = '(?<!^.{0,3}).(?!.{0,3}$)';
    String replacement = '*';
    for (Exam_Voucher__c examVoucher : examVouchers) {
      //voucher.Voucher_Code_Masked__c = 'masked'+voucher.Voucher_Code__c;
      examVoucher.Voucher_Code_Masked__c = examVoucher.Voucher_Code__c.replaceAll(regExp, replacement);
    }
    return examVouchers;
  }

  public static List<Exam_Voucher__c> unsetVoucherCode(
    List<Exam_Voucher__c> vouchers
  ) {
    for (Exam_Voucher__c voucher : vouchers) {
      voucher.Voucher_Code__c = null;
    }
    return vouchers;
  }

  private static Practice_Studio_Setting__mdt getEncryptionConfig() {
    Practice_Studio_Setting__mdt[] appSettings = [SELECT MasterLabel, QualifiedApiName, Algorithm_Name__c ,Initialization_Vector__c, Private_Key__c FROM Practice_Studio_Setting__mdt];
    if(appSettings.size() == 0)
    throw new ExamVoucherException('Encryption config not defined');
    return appSettings[0];
  }
}