force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/Credential_Exam_Attempt__c.object-meta.xml
<CustomObject>
    <label>Credential Exam Attempt</label>
    <nameField>
        <displayFormat>EXAM-{00000}</displayFormat>
        <label>Credential Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <formula>User_Credential__r.Credential__r.Name</formula>
    <label>Credential</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Exam_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Exam_Date_Time__c</fullName>
    <label>Exam Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Exam_Voucher__c.field-meta.xml
<CustomField>
    <fullName>Exam_Voucher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Exam Voucher</label>
    <referenceTo>Exam_Voucher__c</referenceTo>
    <relationshipLabel>Credential Exam Attempts</relationshipLabel>
    <relationshipName>Credential_Exam_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Fail_Scorecard__c.field-meta.xml
<CustomField>
    <fullName>Fail_Scorecard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fail Scorecard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voucher Requested</fullName>
            </value>
            <value>
                <fullName>Voucher Approved</fullName>
            </value>
            <value>
                <fullName>Voucher Declined</fullName>
            </value>
            <value>
                <fullName>Voucher Assigned</fullName>
            </value>
            <value>
                <fullName>Exam Scheduled</fullName>
            </value>
            <value>
                <fullName>Exam Passed</fullName>
            </value>
            <value>
                <fullName>Exam Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <formula>User_Credential__r.User__r.FirstName + &quot; &quot; +  User_Credential__r.User__r.LastName</formula>
    <label>User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/Exam_Voucher__c.object-meta.xml
<CustomObject>
    <label>Exam Voucher</label>
    <nameField>
        <displayFormat>VC-{000000}</displayFormat>
        <label>Exam Voucher ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam_Voucher__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <formula>Credential_Exam_Attempt__r.User_Credential__r.Credential__r.Name</formula>
    <label>Credential</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Credential_Exam_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Credential_Exam_Attempt__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credential Exam Attempt</label>
    <referenceTo>Credential_Exam_Attempt__c</referenceTo>
    <relationshipLabel>Exam Vouchers</relationshipLabel>
    <relationshipName>Exam_Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <formula>Credential_Exam_Attempt__r.User_Credential__r.User__r.FirstName + &quot; &quot; +  Credential_Exam_Attempt__r.User_Credential__r.User__r.LastName</formula>
    <label>User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CredentialExamAttemptService.cls
/**
 * @author Dipshika Nalawade
 * @date   04/08/2022
 * @description Service Class containing methods specific to Credential Exam Attempt
 */
public with sharing class CredentialExamAttemptService {
    /*******************************************************************************************************
      * @description This method retrieves exam attempts for given user
      * @param userId SF id of user
      * @return List of Credential Exam Attempt
      */
     @AuraEnabled(cacheable=true)
     public static List<Credential_Exam_Attempt__c> getExamAttemptsForUser(String userId) {
         try {
             return [
                 SELECT id, Credential__c, Exam_Date_Time__c, Name, Exam_Voucher__c, Fail_Scorecard__c, Status__c,User__c
                 FROM Credential_Exam_Attempt__c
                 WHERE Name= :userId AND (Credential_Exam_Attempt__c.Status__c != 'Completed' OR Credential_Exam_Attempt__c.Status__c != 'Exam Passed' OR Credential_Exam_Attempt__c.Status__c != 'Exam Failed')];
         } catch (Exception ex) {
             throw ex;
         }
     }
      /*******************************************************************************************************
      * @description This method creates exam attempt record
      * @param userId SF id of user
      * @return List of create Exam Attempt
      */
         public List<Database.SaveResult> createExamAttempt(List<Credential_Exam_Attempt__c> examAttemptRecords){
             try {
                 return Database.insert(examAttemptRecords, true);
             } catch (Exception ex) {
                 throw ex;
             }
         }
     /*******************************************************************************************************
      * @description This method updates exam date for a given Exam attempt record
      * @param userId SF id of user
      * @return Update Exam Date
      */
      public Database.SaveResult updateExamDate(String examAttemptRecordId, DateTime dt){
         try {
             Credential_Exam_Attempt__c credExamAttempt = new Credential_Exam_Attempt__c();
             credExamAttempt.Id = examAttemptRecordId;
             credExamAttempt.Exam_Date_Time__c = dt;
             return Database.update(credExamAttempt, true);
         } catch (Exception ex) {
             throw ex;
         }
      }
 
      /*******************************************************************************************************
      * @description This method updates exam attempt status
      * @param userId SF id of user
      * @return Update Exam Status
      */
      public Database.SaveResult updateExamStatus(String examAttemptRecordId, String examStatus){
         try {
             Credential_Exam_Attempt__c examAttempt = new Credential_Exam_Attempt__c();
             examAttempt.Id = examAttemptRecordId;
             examAttempt.Status__c = examStatus;
             return Database.update(examAttempt, true);
         } catch (Exception ex) {
             throw ex;
         }
      }
 }