force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/Credential_Exam_Attempt__c.object-meta.xml
<CustomObject>
    <label>Credential Exam Attempt</label>
    <nameField>
        <displayFormat>EXAM-{00000}</displayFormat>
        <label>Credential Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <formula>User_Credential__r.Credential__r.Name</formula>
    <label>Credential</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Exam_Voucher__c.field-meta.xml
<CustomField>
    <fullName>Exam_Voucher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Exam Voucher</label>
    <referenceTo>Exam_Voucher__c</referenceTo>
    <relationshipLabel>Credential Exam Attempts</relationshipLabel>
    <relationshipName>Credential_Exam_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voucher Requested</fullName>
            </value>
            <value>
                <fullName>Voucher Approved</fullName>
            </value>
            <value>
                <fullName>Voucher Declined</fullName>
            </value>
            <value>
                <fullName>Voucher Assigned</fullName>
            </value>
            <value>
                <fullName>Exam Scheduled</fullName>
            </value>
            <value>
                <fullName>Exam Passed</fullName>
            </value>
            <value>
                <fullName>Exam Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/User_Credential__c.field-meta.xml
<CustomField>
    <fullName>User_Credential__c</fullName>
    <label>User Credential</label>
    <referenceTo>User_Credential__c</referenceTo>
    <relationshipLabel>Credential Exam Attempts</relationshipLabel>
    <relationshipName>Credential_Exam_Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <label>Voucher Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/Exam_Voucher__c.object-meta.xml
<CustomObject>
    <label>Exam Voucher</label>
    <nameField>
        <displayFormat>VC-{000000}</displayFormat>
        <label>Exam Voucher ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam_Voucher__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <formula>Credential_Exam_Attempt__r.User_Credential__r.Credential__r.Name</formula>
    <label>Credential</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Credential_Exam_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Credential_Exam_Attempt__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credential Exam Attempt</label>
    <referenceTo>Credential_Exam_Attempt__c</referenceTo>
    <relationshipLabel>Exam Vouchers</relationshipLabel>
    <relationshipName>Exam_Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Voucher Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Exam_Voucher__c/fields/Voucher_Code_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code_Encrypted__c</fullName>
    <label>Voucher Code Encrypted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Credential__c/User_Credential__c.object-meta.xml
<CustomObject>
    <label>User Credential</label>
    <nameField>
        <displayFormat>CRED-{00000}</displayFormat>
        <label>User Credential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Credential__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <referenceTo>Credential__c</referenceTo>
    <relationshipLabel>User Credentials</relationshipLabel>
    <relationshipName>User_Credentials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/User_Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExamVoucherServiceTest.cls
@IsTest
private class ExamVoucherServiceTest {
    @TestSetup
    static void makeData() {
        TestDataFactory.createExamVoucher();
    }
    @isTest
    private static void getExamVoucherCodeTest() {
        User usr = TestDataFactory.createUser();
        TestDataFactory.assignPboAdminPermissions(usr);
        System.runAs(usr) {
            Exam_Voucher__c examVoucher = [SELECT Voucher_Code__c, Voucher_Code_Encrypted__c FROM Exam_Voucher__c];
            String decryptedMessage = EncryptDecryptService.getInstance().decryptData(examVoucher.Voucher_Code_Encrypted__c);
            System.assertNotEquals(decryptedMessage, null);
            System.assertEquals(null, examVoucher.Voucher_Code__c);
        }

    }
    static testMethod void getAvailableExamVouchersTest() {
        Test.startTest();
        try {
            ExamVoucherService ces = new ExamVoucherService();
            ces.getAvailableExamVouchers('trailhead', 400);
        } catch (Exception ex) {
            system.assert(ex.getMessage().contains('Insufficient permissions'));
        }
        Test.stopTest();
    }

    @isTest
    private static void sendAssignedEmailTest() {
        User usr = TestDataFactory.createUser();
        TestDataFactory.assignPboAdminPermissions(usr);

        System.runAs(usr) {
            List<Credential__c> credList = TestDataFactory.createCredentials();
            User_Credential__c uc = TestDataFactory.createUserCredentials(usr.Id, credList[0].Id);
            insert uc;
            List<Credential_Exam_Attempt__c> credAttempts = TestDataFactory.createCredentialExamAttempt(uc.Id);
            insert credAttempts;
            Credential_Exam_Attempt__c credAttempt = [SELECT id FROM Credential_Exam_Attempt__c][0];
            Exam_Voucher__c voucher = TestDataFactory.getExamVoucher();
            insert voucher;
            Exam_Voucher__c voucherToUpdate = new Exam_Voucher__c(
                Id = voucher.Id,
                Credential_Exam_Attempt__c = credAttempt.Id,
                Status__c = 'Assigned'
            );
            update voucherToUpdate;
            System.assertEquals(1, Limits.getEmailInvocations(), 'Emails should be sent');
        }

    }
}