force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/EU_Target__c.field-meta.xml
<CustomField>
    <fullName>EU_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>EU Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/IN_Target__c.field-meta.xml
<CustomField>
    <fullName>IN_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IN Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <label>Program Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L2</fullName>
            </value>
            <value>
                <fullName>L3</fullName>
            </value>
            <value>
                <fullName>L4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Registration_fee__c.field-meta.xml
<CustomField>
    <fullName>Registration_fee__c</fullName>
    <label>Registration fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Retake_fee__c.field-meta.xml
<CustomField>
    <fullName>Retake_fee__c</fullName>
    <label>Retake fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trailhead</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>MuleSoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential__c/fields/US_Target__c.field-meta.xml
<CustomField>
    <fullName>US_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>US Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Visible_in_Partner_Community_Cert_Tab__c.field-meta.xml
<CustomField>
    <fullName>Visible_in_Partner_Community_Cert_Tab__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible in Partner Community Cert Tab</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/Credential_Exam_Attempt__c.object-meta.xml
<CustomObject>
    <label>Credential Exam Attempt</label>
    <nameField>
        <displayFormat>EXAM-{00000}</displayFormat>
        <label>Credential Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <formula>User_Credential__r.Credential__r.Name</formula>
    <label>Credential</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Exam_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Exam_Date_Time__c</fullName>
    <label>Exam Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Fail_Scorecard__c.field-meta.xml
<CustomField>
    <fullName>Fail_Scorecard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fail Scorecard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Pass_Certificate__c.field-meta.xml
<CustomField>
    <fullName>Pass_Certificate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass Certificate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Preparation_Comments__c.field-meta.xml
<CustomField>
    <fullName>Preparation_Comments__c</fullName>
    <label>Preparation Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Proof_of_Preparation__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Preparation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Preparation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voucher Requested</fullName>
            </value>
            <value>
                <fullName>Voucher Approved</fullName>
            </value>
            <value>
                <fullName>Voucher Declined</fullName>
            </value>
            <value>
                <fullName>Voucher Assigned</fullName>
            </value>
            <value>
                <fullName>Exam Scheduled</fullName>
            </value>
            <value>
                <fullName>Exam Passed</fullName>
            </value>
            <value>
                <fullName>Exam Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/User_Credential__c.field-meta.xml
<CustomField>
    <fullName>User_Credential__c</fullName>
    <label>User Credential</label>
    <referenceTo>User_Credential__c</referenceTo>
    <relationshipLabel>Credential Exam Attempts</relationshipLabel>
    <relationshipName>Credential_Exam_Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Credential__c/User_Credential__c.object-meta.xml
<CustomObject>
    <label>User Credential</label>
    <nameField>
        <displayFormat>CRED-{00000}</displayFormat>
        <label>User Credential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Credential__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <referenceTo>Credential__c</referenceTo>
    <relationshipLabel>User Credentials</relationshipLabel>
    <relationshipName>User_Credentials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/User_Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Credential__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>Credential__r.URL__c</formula>
    <label>URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MultiRecordsApprovalControllerTest.cls
@isTest
public class MultiRecordsApprovalControllerTest {
  public static testMethod void method1(){
     MultiRecordsApprovalController.SubmittedRecordsWrapper mst = new MultiRecordsApprovalController.SubmittedRecordsWrapper();
      
              Credential__c cred =      new Credential__c(            
            Alias__c= 'Salesforce Certified Platform Developer II',
            EU_Target__c = 3,
            External_ID__c = 'Platform_Developer_II',
            IN_Target__c = 4,
            Icon__c = 'https://res.cloudinary.com/kolaliam/image/upload/v1650355111/Salesforce%20Badges/Platform_Developer_II_mecgf5.png',
            Name = 'Platform Developer II',
            Program_Level__c = 'L3',
            
            Registration_fee__c = 200,
            Retake_fee__c = 100,
            Status__c = 'Active',
            Type__c = 'Trailhead',
            URL__c = 'https://trailhead.salesforce.com/help?article=Salesforce-Certified-Platform-Developer-II-Exam-Guide',
            US_Target__c = 2,
            Visible_in_Partner_Community_Cert_Tab__c = true);
        insert cred;
     
        User_Credential__c uc = testDataFactory.createUserCredentials(userInfo.getUserId(), cred.Id);
        insert uc;
        
        
        Credential_Exam_Attempt__c exam = new Credential_Exam_Attempt__c(
            
            Exam_Date_Time__c=system.today(),
            Status__c='Voucher Requested',
            Fail_Scorecard__c=true,
            Pass_Certificate__c=true,
            Preparation_Comments__c='prepared',
            Proof_of_Preparation__c=true,
            User_Credential__c=uc.Id);
            insert exam;
         User user1 = [SELECT Id FROM User WHERE Profile.Name='System administrator' limit 1];

  /*      Approval.ProcessSubmitRequest req =     new Approval.ProcessSubmitRequest();
      req.setComments('Submitting request for approval via form');
      req.setObjectId(exam.Id);
     
      //Step 3:  Submit on behalf of a specific submitter
      req.setSubmitterId(UserInfo.getUserId()); 
   
      //Step 4:  Submit the record to specific process and skip the criteria evaluation
      req.setProcessDefinitionNameOrId('Test_Approval');
      req.setSkipEntryCriteria(true);

      //Step 5:  Submit the approval request for the bid
      Approval.ProcessResult result = Approval.process(req);
*/
      

        Integer intvar = MultiRecordsApprovalController.gettotalcount();
       List<MultiRecordsApprovalController.SubmittedRecordsWrapper> prorec = new List<MultiRecordsApprovalController.SubmittedRecordsWrapper>();
        prorec = MultiRecordsApprovalController.getSubmittedRecords(5,0);
        string resultrec = MultiRecordsApprovalController.processRecords('Approve',Json.serialize(prorec));
      MultiRecordsApprovalController.getObjectName(exam.Id);
      MultiRecordsApprovalController.IncreaseCoverage();
    }
    
}