force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CredentialSearchController.cls
public  class CredentialSearchController {
  
    @AuraEnabled(cacheable=true)
    public static List <Credential__c> getCredentials(String searchKeyWord) {
     String searchKey = searchKeyWord + '%';
     List <Credential__c> returnCredentials = new List <Credential__c> ();
     List <Credential__c> lstOfCredentials = [select id,Name,Icon__c from Credential__c where Name LIKE: searchKey];
    
     for (Credential__c credentials: lstOfCredentials) {
        returnCredentials.add(credentials);
       
        }
     return returnCredentials;
    } 

    @AuraEnabled(cacheable=true)
    public static List <Credential__c> getCredName() {
         return [select id,Name,Icon__c from Credential__c];
        
    }
}