force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Badge_Icon__c.field-meta.xml
<CustomField>
    <fullName>Badge_Icon__c</fullName>
    <formula>IMAGE(Icon__c , Name , 50, 50)</formula>
    <label>Badge Icon</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Credential__c/User_Credential__c.object-meta.xml
<CustomObject>
    <label>User Credential</label>
    <nameField>
        <displayFormat>CRED-{00000}</displayFormat>
        <label>User Credential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Credential__c/fields/Badge_Icon__c.field-meta.xml
<CustomField>
    <fullName>Badge_Icon__c</fullName>
    <formula>Credential__r.Badge_Icon__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Badge Icon</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Credential__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <referenceTo>Credential__c</referenceTo>
    <relationshipLabel>User Credentials</relationshipLabel>
    <relationshipName>User_Credentials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/apecExample1.cls
public with sharing class apecExample1 {
    

    @AuraEnabled(cacheable=true)
    public static List <User> getResults(String searchKeyWord) {
     String searchKey = searchKeyWord + '%';
     List <User> returnList = new List < User > ();
     List <User> lstOfUsers = [select id, Name,UserRole.Name,Title from User where Name LIKE: searchKey];
    
     for (User users: lstOfUsers) {
        returnList.add(users);
       
        }
     return returnList;
    }

    @AuraEnabled(cacheable=true)
    public static List <User_Credential__c> getCredentials(String searchKeyWord) {
     String searchKey = searchKeyWord + '%';
     List <User_Credential__c> returnCredentials = new List <User_Credential__c> ();
     List <User_Credential__c> lstOfUsers = [select id,Name, Badge_Icon__c,Credential__r.name from User_Credential__c where Name LIKE: searchKey];
    
     for (User_Credential__c credentials: lstOfUsers) {
        returnCredentials.add(credentials);
       
        }
     return returnCredentials;
    }
    
   
}