force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Exam_Attempt__c/Credential_Exam_Attempt__c.object-meta.xml
<CustomObject>
    <label>Credential Exam Attempt</label>
    <nameField>
        <displayFormat>EXAM-{00000}</displayFormat>
        <label>Credential Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <formula>User_Credential__r.Credential__r.Name</formula>
    <label>Credential</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExamScheduleController.cls
public with sharing class ExamScheduleController {
    @AuraEnabled(cacheable = true)
     public static map<string , object> getExamDetails(string examId){
         map<string , object> returnMap = new map<string , object> ();
         list<Credential_Exam_Attempt__c> CredentialsExamAttemptList = [select id , name,Credential__c from Credential_Exam_Attempt__c  where id =:examId];
         returnmap.put('ExamId',CredentialsExamAttemptList[0].NaMe);
         returnmap.put('credentialId',CredentialsExamAttemptList[0].Credential__c);
         return returnMap;    
     }
     
     
     @AuraEnabled()
     public static string UpdateCredExempt(Credential_Exam_Attempt__c examAttemptRec){
           update examAttemptRec;
         return examAttemptRec.Id;
         
         
     }
   
   @AuraEnabled()
          public static string UploadReciept(string ParentId ,list<string> filedata){
             system.debug('StrId'+ParentId);
        
         try {
             if(filedata.size()>0) {
                FilesUploadService fp = new FilesUploadService();
                fp.uploadFiles(ParentId, filedata);
              
             }
                      
         } catch (Exception ex) {
             System.debug(ex.getMessage() + ' -> ' + ex.getStackTraceString());
             throw new AuraHandledException(ex.getMessage());
         }
              
              return 'Success';    
          }
 
 }