force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Credential__c/User_Credential__c.object-meta.xml
<CustomObject>
    <label>User Credential</label>
    <nameField>
        <displayFormat>CRED-{00000}</displayFormat>
        <label>User Credential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Credential__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <referenceTo>Credential__c</referenceTo>
    <relationshipLabel>User Credentials</relationshipLabel>
    <relationshipName>User_Credentials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/User_Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CredentialsOfSubordinatesAPEX_Test.cls
@IsTest
public with sharing class CredentialsOfSubordinatesAPEX_Test {
    @TestSetup
    static void makeData(){
        TestDataFactory.createCredentials();        
    }
    @IsTest
    public static void getCredentialsOfSubordinates_Test() {
        User usr = TestDataFactory.createUser();
        TestDataFactory.assignPboAdminPermissions(usr);
        User subordinate = TestDataFactory.createUser();
        TestDataFactory.assignPboAdminPermissions(subordinate);
        subordinate.ManagerId=usr.Id;
        update subordinate;
        System.runAs(usr){
            Credential__c credential = [Select id,name from Credential__c where name = 'Platform Developer II'][0];
            User_Credential__c usrCredential = TestDataFactory.createUserCredentials(subordinate.Id,credential.id);
            usrCredential.Status__c = 'Preparing';
            insert usrCredential;
            system.debug(usrCredential);
            Test.startTest();
            List<CredentialsOfSubordinatesAPEX.subordinateCredentialsInfo> sciList = CredentialsOfSubordinatesAPEX.getCredentialsOfSubordinates(usr.Id);
            Test.stopTest();
        }
    }
}