force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Badge_Icon__c.field-meta.xml
<CustomField>
    <fullName>Badge_Icon__c</fullName>
    <formula>IMAGE(Icon__c , Name , 50, 50)</formula>
    <label>Badge Icon</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Smaller numbers indicate higher priority.</description>
    <inlineHelpText>Smaller numbers indicate higher priority.</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CredentialPrioritizeController.cls
/**
 * @author Nitin Savanur
 * @date   9/12/2022
 * @description Apex controller for credentialPrioratize component
 */
public with sharing class CredentialPrioritizeController {
	/*******************************************************************************************************
	 * @description Returns Credential__c that have Priority set
	 * @return List of Credential__c
	 */
	@AuraEnabled
	public static List<Credential__c> getRecords() {
		try {
			return Database.query(
				'Select id, name, Badge_Icon__c,Icon__c from Credential__c where Priority__c != null order by Priority__c asc'
			);
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*******************************************************************************************************
	 * @description Method to update Priority for Credentials
	 */
	@AuraEnabled
	public static void updatePriority(String recordList) {
		try {
			List<Credential__c> credentialList = (List<Credential__c>) JSON.deserialize(
				recordList,
				List<Credential__c>.class
			);
			Database.update(credentialList, true);
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}