force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Smaller numbers indicate higher priority.</description>
    <inlineHelpText>Smaller numbers indicate higher priority.</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CredentialPrioritizeControllerTest.cls
@IsTest
private class CredentialPrioritizeControllerTest {
	@TestSetup
	static void makeData() {
		TestDataFactory.createUser();
		TestDataFactory.createCredentials();
	}

	@IsTest
	private static void getRecordsTest() {
		User usr = [SELECT id FROM User WHERE Email = 'puser000@amamama.com'];
		System.runAs(usr) {
			List<Credential__c> creds = CredentialPrioritizeController.getRecords();
			System.assertEquals(1, creds.size(), 'sucsess check');
		}
	}

	@IsTest
	private static void updatePriorityTest() {
		String recId = [SELECT Id FROM Credential__c WHERE Name = 'Platform Developer I'][0].Id;
		String recJson = '[{"Id":"' + recId + '","Priority__c":2}]';
		CredentialPrioritizeController.updatePriority(recJson);
		System.assertEquals(
			2,
			[SELECT Priority__c FROM Credential__c WHERE id = :recId][0]
			.Priority__c,
			'Success check'
		);
	}
}