force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>A certification or accreditation or any other knowledge achievement.</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <label>Program Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L2</fullName>
            </value>
            <value>
                <fullName>L3</fullName>
            </value>
            <value>
                <fullName>L4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trailhead</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>MuleSoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Visible_in_Partner_Community_Cert_Tab__c.field-meta.xml
<CustomField>
    <fullName>Visible_in_Partner_Community_Cert_Tab__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible in Partner Community Cert Tab</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/Credential_Exam_Attempt__c.object-meta.xml
<CustomObject>
    <label>Credential Exam Attempt</label>
    <nameField>
        <displayFormat>EXAM-{00000}</displayFormat>
        <label>Credential Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <formula>User_Credential__r.Credential__r.Name</formula>
    <label>Credential</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Preparation_Comments__c.field-meta.xml
<CustomField>
    <fullName>Preparation_Comments__c</fullName>
    <label>Preparation Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Proof_of_Preparation__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Preparation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Preparation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voucher Requested</fullName>
            </value>
            <value>
                <fullName>Voucher Approved</fullName>
            </value>
            <value>
                <fullName>Voucher Declined</fullName>
            </value>
            <value>
                <fullName>Voucher Assigned</fullName>
            </value>
            <value>
                <fullName>Exam Scheduled</fullName>
            </value>
            <value>
                <fullName>Exam Passed</fullName>
            </value>
            <value>
                <fullName>Exam Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <formula>User_Credential__r.User__r.FirstName + &quot; &quot; +  User_Credential__r.User__r.LastName</formula>
    <label>User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_Exam_Attempt__c/fields/User_Credential__c.field-meta.xml
<CustomField>
    <fullName>User_Credential__c</fullName>
    <label>User Credential</label>
    <referenceTo>User_Credential__c</referenceTo>
    <relationshipLabel>Credential Exam Attempts</relationshipLabel>
    <relationshipName>Credential_Exam_Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Credential__c/User_Credential__c.object-meta.xml
<CustomObject>
    <label>User Credential</label>
    <nameField>
        <displayFormat>CRED-{00000}</displayFormat>
        <label>User Credential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Credential__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <referenceTo>Credential__c</referenceTo>
    <relationshipLabel>User Credentials</relationshipLabel>
    <relationshipName>User_Credentials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/User_Credential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Credential__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Credentials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FilesUploadServiceTest.cls
@isTest(seeAllData=false)
public class FilesUploadServiceTest {
    public static testMethod void documnetsUploadTest()
    {
          Profile pf= [Select Id from profile where Name='System Administrator']; 
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer randId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+randId; 
        User uu=new User(firstname = 'ABC', 
                         lastName = 'XYZ', 
                         email = uniqueName + '@test' + orgId + '.org', 
                         Username = uniqueName + '@test' + orgId + '.org', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         ProfileId = pf.Id
                        ); 
        insert uu;

        
        Credential__c crObj = new Credential__c(Name='Service Cloud Consultant',
                                                Type__c='Trailhead',
                                                Status__c='Active',
                                                Program_Level__c='L1',
                                                Visible_in_Partner_Community_Cert_Tab__c=True
                                               );
        insert crObj;
        User_Credential__c ucObj = new User_Credential__c(Credential__c =crObj.id,
                                                          User__c =uu.id,
                                                          Status__c='Ready'
                                                         );
      
        
        
        
          insert ucObj;
        Credential_Exam_Attempt__c ceaObj = new Credential_Exam_Attempt__c(User_Credential__c=ucObj.Id,
                                                                           Preparation_Comments__c='Test comments',
                    
                                                                           
                                                                         Proof_of_Preparation__c=True);
        
        string recId = VoucherRequestController.createCredExempt(ceaObj);
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;
        
        Contact cont = new Contact ();
        cont.FirstName = 'FirstName';
        cont.LastName = 'LastName';
        cont.Email='email@email.com';
        cont.phone='12345678';
        insert cont;
        
        Account acct = new Account(Name='TEST_ACCT');
        insert acct;
        List<contentVersion> version = new List<contentVersion>();
        List<map<string,object>> vers = new List<map<string,object>>();
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        version.add(contentVersion);
        database.insert(version);
        
         
        string before = 'Testing encoding record';
        Blob beforeblob = Blob.valueOf(before);
        string paramvalue = EncodingUtil.base64Encode(beforeblob);        
        Map<String,Object> mapContent = new Map<String,Object>{ 'fileContent' => paramvalue , 'fileName' => 'Test'};
       
        
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        vers.add(mapContent);
         
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = acct.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        
       
        Test.startTest();
     FilesUploadService.FileDataWP obj = new FilesUploadService.FileDataWP();
        obj.fileContent = paramvalue;
        obj.fileName = 'test';
        
        list<FilesUploadService.FileDataWP> filelist = new list<FilesUploadService.FileDataWP>();
        
        filelist.add(obj);
        string file = json.serialize(filelist);
     
        list<string> files = new list<string>();
        files.add(file);
            
    	 FilesUploadService.uploadFiles(recId, files);
          Test.stopTest();
    }
    
    
}