force-app/main/default/objects/Quick_Links_Setting__mdt/Quick_Links_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Quick Links Setting</label>
    <pluralLabel>Quick Links Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Quick_Links_Setting__mdt/fields/Button_Label__c.field-meta.xml
<CustomField>
    <fullName>Button_Label__c</fullName>
    <label>Button Label</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quick_Links_Setting__mdt/fields/Component_Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Action_Type__c</fullName>
    <description>Applicable only for Components</description>
    <label>Component Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Modal Popup</fullName>
                <default>true</default>
                <label>Modal Popup</label>
            </value>
            <value>
                <fullName>Navigation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quick_Links_Setting__mdt/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <inlineHelpText>Applicable only if Navigation is Component Type</inlineHelpText>
    <label>Component Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quick_Links_Setting__mdt/fields/Navigation_Type__c.field-meta.xml
<CustomField>
    <fullName>Navigation_Type__c</fullName>
    <label>Navigation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>URL</fullName>
                <default>true</default>
                <label>URL</label>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Tab</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quick_Links_Setting__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quick_Links_Setting__mdt/fields/Redirection_URL__c.field-meta.xml
<CustomField>
    <fullName>Redirection_URL__c</fullName>
    <label>Redirection URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Quick_Links_Setting__mdt/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <label>Section Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuickLinkController.cls
public with sharing class QuickLinkController {
    @AuraEnabled( cacheable=true )  
    public static  Map<String,List<Quick_Links_Setting__mdt>> fetchQuickLinksList() {
        Map<String,List<Quick_Links_Setting__mdt>> quickLinkMap=new Map<String,List<Quick_Links_Setting__mdt>>();
        List < Quick_Links_Setting__mdt > fetchMetadata = [ SELECT Id,Button_Label__c,Section_Name__c,Order__c,Redirection_URL__c,Component_Action_Type__c,Navigation_Type__c,Component_Name__c  FROM Quick_Links_Setting__mdt order by Order__c];
        for(Quick_Links_Setting__mdt metaData:fetchMetadata)
        { 
            List<Quick_Links_Setting__mdt> buttonList= quickLinkMap.get(metaData.section_Name__c);
            if(buttonList==null)
            {
                buttonList=new List<Quick_Links_Setting__mdt>();
                buttonList.add(metaData);
                quickLinkMap.put(metaData.section_Name__c,buttonList);
            }
            else 
            {
                buttonList.add(metaData);
                quickLinkMap.put(metaData.section_Name__c,buttonList);
            }

        }

        return quickLinkMap;

    }
}